source 'https://gitlab.enncloud.cn/FNMobileTeam/FNSpecRepos.git'
source 'https://github.com/GuoSX2014/FN_SpecRepos.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'FN_Base_Example' do
  pod 'FN_Base', :path => '../'

  target 'FN_Base_Tests' do
    inherit! :search_paths
    
  end
end
